name: itemdetect
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.5.1
      - opencv-python==4.13.0.92
      - numpy==2.4.4
      - pandas==3.0.3
      - Pillow==12.2.0
      - PyYAML==6.0.3
      - tqdm==4.67.3
      - onnx==1.21.0
      - onnxruntime==1.24.4
